;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GameplayCue.FX.Block",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.Parry",DevComment="패링성공 게임플레이큐")
+GameplayTagList=(Tag="GameplayCue.FX.SuccessfulBlock",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sounds.Melee.Nodachi",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sounds.Melee.Sword",DevComment="")

