;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Statetree.Task.FindBetterSlot",NewTagName="Statetree.Task.FindSlotInGivenActor")
+GameplayTagRedirects=(OldTagName="StateTree.SmartObject.MotionMatch.CostSucess",NewTagName="StateTree.SmartObject.MotionMatch.CostSuccess")
+GameplayTagRedirects=(OldTagName="SmartObject.ObjectType.FoodTruck",NewTagName="SmartObject.ObjectType.QueSmartObject")
+GameplayTagRedirects=(OldTagName="Player.ActionTag.Attacking",NewTagName="Player.ActionState.Attacking")
+GameplayTagRedirects=(OldTagName="Player.ActionTag.Dodging",NewTagName="Player.ActionState.Dodging")
+GameplayTagRedirects=(OldTagName="Player.ActionTag.LastAttack.Jump",NewTagName="Player.ActionState.LastAttack.Jump")
+GameplayTagRedirects=(OldTagName="Player.ActionTag.LastAttack.Land",NewTagName="Player.ActionState.LastAttack.Land")
+GameplayTagRedirects=(OldTagName="Player.ActionTag.LastAttack",NewTagName="Player.ActionState.LastAttack")
+GameplayTagRedirects=(OldTagName="Player.ActionTag",NewTagName="Player.ActionState")
+GameplayTagRedirects=(OldTagName="Shared.Status.Groggy",NewTagName="Shared.Status.PostureBroken")
+GameplayTagRedirects=(OldTagName="Shared.Event.GroggyTriggered",NewTagName="Shared.Event.PostureBrokenTriggered")
+GameplayTagRedirects=(OldTagName="Shared.SetByCaller.GroggyDamage",NewTagName="Shared.SetByCaller.PostureDamage")
+GameplayTagRedirects=(OldTagName="Shared.Ability.Groggy",NewTagName="Shared.Ability.PostureBroken")
+GameplayTagRedirects=(OldTagName="Player.Ability.Execution",NewTagName="Player.Ability.CriticalAttack")
+GameplayTagRedirects=(OldTagName="Player.Status.Executing",NewTagName="Player.Status.CriticalAttacking")
+GameplayTagRedirects=(OldTagName="Shared.Event.ExecutionDamage",NewTagName="Shared.Event.CriticalAttackDamage")
+GameplayTagRedirects=(OldTagName="Shared.SetByCaller.ExecutionDamage",NewTagName="Shared.SetByCaller.CriticalAttackDamage")
+GameplayTagRedirects=(OldTagName="Enemy.Status.Attacking.Commited",NewTagName="Enemy.Status.Attacking.Swing")
+GameplayTagList=(Tag="Abilities.ContextualAnim",DevComment="")
+GameplayTagList=(Tag="Abilities.MoveTo",DevComment="")
+GameplayTagList=(Tag="Enemy.Ability.AttackType.Combo",DevComment="")
+GameplayTagList=(Tag="Enemy.Ability.AttackType.Combo.Phase2",DevComment="")
+GameplayTagList=(Tag="Enemy.Ability.Pressure.Flowup",DevComment="")
+GameplayTagList=(Tag="Enemy.Cooldown.Attack.Combo",DevComment="")
+GameplayTagList=(Tag="Enemy.Cooldown.Attack.Combo.Phase2",DevComment="")
+GameplayTagList=(Tag="Enemy.Cooldown.Block",DevComment="")
+GameplayTagList=(Tag="Enemy.Cooldown.Dodge",DevComment="")
+GameplayTagList=(Tag="Enemy.Status.Attacking.Swing",DevComment="")
+GameplayTagList=(Tag="Enemy.Status.ComboInProgress",DevComment="")
+GameplayTagList=(Tag="Enemy.Status.ComboInProgress.Phase2",DevComment="")
+GameplayTagList=(Tag="Enemy.Status.Pressure.FlowupAttacking",DevComment="")
+GameplayTagList=(Tag="Foley",DevComment="")
+GameplayTagList=(Tag="Foley.Event",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Handplant",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Jump",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Land",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Run",DevComment="")
+GameplayTagList=(Tag="Foley.Event.RunBackwds",DevComment="")
+GameplayTagList=(Tag="Foley.Event.RunStrafe",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Scuff",DevComment="")
+GameplayTagList=(Tag="Foley.Event.ScuffPivot",DevComment="")
+GameplayTagList=(Tag="Foley.Event.ScuffWall",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Slide.Loop",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Tumble",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Walk",DevComment="")
+GameplayTagList=(Tag="Foley.Event.WalkBackwds",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ContextualAnim",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.Block",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.Enemy.AshenKnight.Parry",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.Enemy.AshenKnight.SuccessfulBlock",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.Parry",DevComment="패링성공 게임플레이큐")
+GameplayTagList=(Tag="GameplayCue.FX.SuccessfulBlock",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sounds.Melee.Nodachi",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sounds.Melee.Sword",DevComment="")
+GameplayTagList=(Tag="MotionMatching",DevComment="")
+GameplayTagList=(Tag="MotionMatching.Default",DevComment="")
+GameplayTagList=(Tag="MotionMatching.Idle",DevComment="")
+GameplayTagList=(Tag="MotionMatching.Loops",DevComment="")
+GameplayTagList=(Tag="MotionMatching.Pivots",DevComment="")
+GameplayTagList=(Tag="MotionMatching.Starts",DevComment="")
+GameplayTagList=(Tag="MotionMatching.Stops",DevComment="")
+GameplayTagList=(Tag="Player.ActionState.Attacking",DevComment="플레이어가 공격중인 상태")
+GameplayTagList=(Tag="Player.ActionState.Dodging",DevComment="플레이어가 닷지중인상태")
+GameplayTagList=(Tag="Player.ActionState.LastAttack.Jump",DevComment="플레이어가 마지막 공격이며 점프상태")
+GameplayTagList=(Tag="Player.ActionState.LastAttack.Land",DevComment="플레이어가 마지막 공격중이며 착지")
+GameplayTagList=(Tag="SmartObject.ObjectType.Bench",DevComment="")
+GameplayTagList=(Tag="SmartObject.ObjectType.NPC",DevComment="")
+GameplayTagList=(Tag="SmartObject.ObjectType.Player",DevComment="")
+GameplayTagList=(Tag="SmartObject.ObjectType.QueSmartObject",DevComment="")
+GameplayTagList=(Tag="StateTree.SmartObject.ExitSmartObject",DevComment="")
+GameplayTagList=(Tag="StateTree.SmartObject.MotionMatch.CostSuccess",DevComment="")
+GameplayTagList=(Tag="Statetree.Task.Climb",DevComment="")

