; PostProcess 품질별 오버라이드.
; 여기 적지 않은 키는 엔진의 BaseScalability.ini 값을 그대로 쓴다.

[PostProcessQuality@0]
r.BloomQuality=4
r.Tonemapper.Quality=0

[PostProcessQuality@1]
r.BloomQuality=4
r.Tonemapper.Quality=0
r.Bloom.ScreenPercentage=25.000

[PostProcessQuality@2]
r.BloomQuality=4
r.Tonemapper.Quality=2
r.Bloom.ScreenPercentage=35.355

[PostProcessQuality@3]
r.BloomQuality=5
r.Tonemapper.Quality=5
r.Bloom.ScreenPercentage=50.000
r.LensFlareQuality=1
r.SceneColorFringeQuality=1
r.DepthOfFieldQuality=3
